# Generated by Django 5.1.3 on 2024-11-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='menusubcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
