# Generated by Django 5.1.3 on 2024-11-14 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menucategory_name_alter_menusubcategory_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='menu_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurant.menusubcategory', verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.dish', verbose_name='Dish'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurant.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='menusubcategory',
            name='menu_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_sub_categories', to='restaurant.menucategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
